###
POST http://localhost:9000/api/users HTTP/1.1
Content-Type: application/json

{
    "user": "Pedro",
    "password": "234234"
    ,
    "firstTime": true,
    "isAdmin": false
}
###
POST http://localhost:9000/api/signin HTTP/1.1
Content-Type: application/json

{
    "user": "Alfredo",
    "password": "gato123"
}

###
GET http://localhost:9000/api/users/ HTTP/1.1

###
GET http://localhost:9000/api/signin/?user=Pedro3000&password=tilinsex HTTP/1.1

###
PUT http://localhost:9000/api/users/641750ef8ae313d095a1c69f HTTP/1.1
Content-Type: application/json

{

    "password": "apz.$",
    "FirstTime?": true,
    "Municipio": "Apozol",
    "isAdmin?": true
}

###
DELETE http://localhost:9000/api/users/64291dbd2ca76d37417b5fd5 HTTP/1.1