###
POST http://localhost:9000/api/users HTTP/1.1
Content-Type: application/json

{
    "user": "Tengris",
    "password": "tanjiro",
    "firstTime": true,
    "isAdmin": false,
    "district": "Z2"
}
###
GET https://ieezapi.onrender.com/api/signin HTTP/1.1
Content-Type: application/json

{
    "user": "Alfredo",
    "password": "gato123"
}

###
GET https://ieezapi.onrender.com/api/users/ HTTP/1.1

###
GET http://localhost:9000/api/signin/?user=Pedro&password=234234 HTTP/1.1

###
PUT http://localhost:9000/api/users/6442c1363186b29db76e341c HTTP/1.1
Content-Type: application/json

{
    "password": "tanjiro",
    "firstTime": true
}

###
DELETE http://localhost:9000/api/users/64291dbd2ca76d37417b5fd5 HTTP/1.1