###
POST http://localhost:9000/api/users HTTP/1.1
Content-Type: application/json

{
    "user": "Alfredo",
    "password": "gato123"
}
###
POST http://localhost:9000/api/signin HTTP/1.1
Content-Type: application/json

{
    "user": "Alfredo",
    "password": "gato123"
}
###
GET http://localhost:9000/api/users HTTP/1.1

###
GET http://localhost:9000/api/users/Pedro HTTP/1.1

###
PUT http://localhost:9000/api/users/64115bf72102f47f3ace8a1f HTTP/1.1
Content-Type: application/json

{
    "nombre": "Alekey Rivas 10",
    "password": "RebotasTula"
}

###
DELETE http://localhost:9000/api/users/641161bb17cf2439b6f03f43 HTTP/1.1